# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Liz Ottosson Scandinavian Translation
description: "Swedish, Danish and Norwegian to English Translation and Localisation, covering a wide range of subjects including marketing, finance, life science and business documents."
keywords: "Tranlation, Localisation, Localization, Swedish, Danish, English, Freelance, Business, Europe"
url: ajlee.github.io
baseurl: "/lizsite"

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
# disqus_shortname: "nandothemes"
# disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Liz Ottosson
  job: Swedish / Danish to English Translator
  bio: "Twenty years of experience in Scandinavian to English translation."
  thumb: /images/author.png
  email: elizabeth.ottosson@gmail.com
  url: https://nandomoreira.me/
  github: https://github.com/???????????
  twitter: https://twitter.com/umdevux
  facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
